### ISSUE TITLE
Directory creation/rights issues

### ISSUE THREAD

**Issue by TerenceMilbourn** [VirtuBox/ubuntu-nginx-web-server#10]
`sudo -u www-data composer update -d /var/www/22222/htdocs/db/pma/`  is not able to create the cache subdirectories composer needs.

**Comment by VirtuBox** [comment]
Hello @TerenceMilbourn ,

I haven't found the time to optimize this command yet, mostly because composer update is working properly without cache (it's probably slower).
Feel free to suggest another way to proceed. At the beginning, I was running the command composer as root before using `chown -R www-data-:www-data /var/www/22222/htdocs` to set back www-data as folder's owner.

**Comment by TerenceMilbourn** [comment]
Hi @VirtuBox -- I did the exact same thing in changing the ownership and wasn't able to get the cache working, which is why I wrote in here.  Sorry but I don't know where tio go from here.

**Comment by VirtuBox** [comment]
Issue has been fixed : 

```
chown www-data:www-data /var/www
sudo -u www-data -H composer update -d /var/www/22222/htdocs/db/pma/
```

**Comment by TerenceMilbourn** [comment]
Cool.  I know its only at beta-3 so far, but how much of what you are doing are planning to move over to EE version 4.x?

**Comment by VirtuBox** [comment]
At the moment, I'm not planning to migrate to EE 4.x, because I'm using EE on servers running in production, and I will have to make sure there are no issues with EE 4.x and to see if the troubleshooting isn't harder with Docker.
