### ISSUE TITLE
webp and Cloudflare CDN cache

### ISSUE THREAD

**Issue by aryaprakasa** [VirtuBox/ubuntu-nginx-web-server#23]
Hi @VirtuBox,

If the images already cached by Cloudflare CDN as a webp, it will serve in all browser as a webp even in an unsupported browser. 

Is there any trick to solve this problem?

**Comment by VirtuBox** [comment]
Hello @aryaprakasa,

WebP images should not be cached and served without the png/jpg alternative due to the header : 
```nginx
add_header Vary "Accept-Encoding";
```
But I will have to check if there are additional settings to set in Cloudflare panel.

However, WebP support will be added in the next Firefox release (65) and is already available in FireFox Beta & Nightly : 

![webp support firefox](https://img.virtubox.net/images/2018/12/13/Screenshot_69.png)

It should be the same for the next release of Microsoft Edge because it will be based on chromium.
So, I expect WebP format to be supported by at least 95% of users in January 2019.

**Comment by aryaprakasa** [comment]
I just do a quick research and it seems this is not possible if using Cloudflare Free.

Is there any plan to add [MozJPEG](https://github.com/mozilla/mozjpeg) to your [img-optimize](https://github.com/VirtuBox/img-optimize) script?
